### Cambiar lang a en
PUT http://localhost:8080/lang/en

### Cambiar lang a es
PUT http://localhost:8080/lang/es

### Cambiar lang a null
PUT http://localhost:8080/lang/


### Obtener códigos
GET http://localhost:8080/codes/
Accept: application/json

### Obtener géneros
GET http://localhost:8080/codes/gender
Accept: application/json

### Obtener marcas
GET http://localhost:8080/codes/card_brand
Accept: application/json

### Obtener monedas
GET http://localhost:8080/codes/currency
Accept: application/json

### Obtener tipos de producto
GET http://localhost:8080/codes/product_types
Accept: application/json

### Obtener tipos de cuit
GET http://localhost:8080/codes/entity_type
Accept: application/json

### Obtener descripcion de los codigos de entidad de los cuits
GET http://localhost:8080/codes/entity_codes
Accept: application/json

### Obtener todos los códigos
GET http://localhost:8080/codes/all
Accept: application/json

