### Listar todos los customers
GET http://localhost:8080/customers
Accept: application/json

### Obtener customer por id
GET http://localhost:8080/customers/107
Accept: application/json

### Obtener customer con id invalido
GET http://localhost:8080/customers/sarasa
Accept: application/json

### Obtener customer con id nulo
GET http://localhost:8080/customers/
Accept: application/json


### Obtener entityType de un Customer
GET http://localhost:8080/customers/140/info
Accept: application/json

### Crear una empresa
POST http://localhost:8080/customers
Content-Type: application/json

{
  "fullName": "CocaCola,ARG",
  "cuit": "30525390086"
}

### Crear una persona
POST http://localhost:8080/customers
Content-Type: application/json

{
  "fullName": "Barrasa, Sebastián Gabriel",
  "cuit": "20240614708",
  "birthDay": "1974-06-07",
  "gender": "M"
}

### Crear otra persona
POST http://localhost:8080/customers
Content-Type: application/json

{
  "fullName": "Perez, Maia",
  "cuit": "23234567119",
  "birthDay": "2001-12-19",
  "gender": "F"
}

### Actualizar un customer
PUT http://localhost:8080/customers/363
Content-Type: application/json

{
  "gender": "X"
}

### Actualizar un customer
PUT http://localhost:8080/customers/109
Content-Type: application/json

{
  "fullName": "Barrasa Rabinovich, Sebastián Gabriel"
}

### Intento de actualizar un id
PUT http://localhost:8080/customers/1
Content-Type: application/json

{
  "id": 10
}

### Actualizar un customer
PUT http://localhost:8080/customers/3
Content-Type: application/json

{
  "cuit": "30123456781"
}


### Eliminar un customer
DELETE http://localhost:8080/customers/299

### Buscar
POST http://localhost:8080/customers/find
Content-Type: application/json

{
}
