### Enviar un customer con products
POST http://localhost:8080/customer/123/products
Content-Type: application/json

{
  "customer": {
    "id": 123
  },
  "products": [
    {
      "type": "CC",
      "cbu": "00000001",
      "currency": "ARS",
      "creditLimit": 10000000.0
    },
    {
      "type": "TD",
      "branch": "VISA",
      "number": "4000111122223333",
      "expirationDate":"1974-06-07"
    }
  ]
}

###