### Listar todos los customers
GET http://localhost:8080/customers
Accept: application/json

### Obtener customer por id
GET http://localhost:8080/customers/1
Accept: application/json

### Obtener customer con id invalido
GET http://localhost:8080/customers/sarasa
Accept: application/json

### Obtener customer con id nulo
GET http://localhost:8080/customers/
Accept: application/json

### Crear un customer
POST http://localhost:8080/customers
Content-Type: application/json

{
  "name": "María",
  "lastName": "Pérez",
  "birthDay": "1985-10-23",
  "gender": "F"

}

### Crear otro customer
POST http://localhost:8080/customers
Content-Type: application/json

{
  "name": "Sebastián Gabriel",
  "lastName": "Barrasa",
  "birthDay": "1974-06-07",
  "gender": "M"
}

### Actualizar un customer
PUT http://localhost:8080/customers/1
Content-Type: application/json

{
  "gender": "X"
}

###

### Eliminar un customer
DELETE http://localhost:8080/customers/1
