### Iniciar servidor web H2
POST http://localhost:8080/db/web/start
Accept: text/plain

### Detener servidor web H2
POST http://localhost:8080/db/web/stop
Accept: text/plain

### Estado del servidor web H2
GET http://localhost:8080/db/web/status
Accept: text/plain

### Iniciar servidor TCP H2
POST http://localhost:8080/db/tcp/start
Accept: text/plain

### Detener servidor TCP H2
POST http://localhost:8080/db/tcp/stop
Accept: text/plain

### Estado del servidor TCP H2
GET http://localhost:8080/db/tcp/status
Accept: text/plain
